#!/bin/bash

set -e
set -x


while getopts "c:d:t:r:" OPTION
do
    case $OPTION in 
        c) CLOUD_CONFIG="$OPTARG" ;;
        d) DEVICE="$OPTARG" ;;
        t) ENV="$OPTARG" ;;
        r) ROLLBACK_VERSION="$OPTARG" ;;
        *) exit 1 ;;
    esac
done

BASE_DIR="/mnt/new_img"

device_defined()
{
    if [[ -z "$1" ]]; then
        echo "Need to Pass a device name as arg1." 1>&2
        exit 1
    fi
}

format_device()
{
    mkfs.ext4 -i 4096 -F -L RANCHER_STATE ${DEVICE}1
}

mount_device() 
{
    local label=RANCHER_STATE

    mkdir -p ${BASE_DIR}

    if [ "$(lsblk -o name|grep RANCHER_BOOT | wc -l)" -eq "1" ]; then
        label=RANCHER_BOOT
    fi
    
    mount -L ${label} ${BASE_DIR}
}

create_boot_dirs()
{
    mkdir -p ${BASE_DIR}/boot/grub
}

install_grub() {
    grub-install --boot-directory=${BASE_DIR}/boot ${DEVICE}
}

grub2_config(){
local grub_cfg=${BASE_DIR}/boot/grub/grub.cfg
cat >$grub_cfg <<EOF
set default="0"
set timeout="1"
#set fallback=1

menuentry "RancherOS-current" {
  set root=(hd0,1)
  linux /boot/vmlinuz-${RANCHEROS_VERSION}-rancheros
  initrd /boot/initrd-${RANCHEROS_VERSION}-rancheros
}

EOF

if [ ! -z $ROLLBACK_VERSION ]; then
    sed -i 's/^#set/set/' ${grub_cfg}
cat >>$grub_cfg <<EOF
menuentry "RancherOS-rollback" {
  set root=(hd0,1)
  linux /boot/vmlinuz-${ROLLBACK_VERSION}-rancheros
  initrd /boot/initrd-${ROLLBACK_VERSION}-rancheros
}
EOF
fi

}

install_rancher()
{
    cp /dist/initrd /mnt/new_img/boot/initrd-${RANCHEROS_VERSION}-rancheros
    cp /dist/vmlinuz /mnt/new_img/boot/vmlinuz-${RANCHEROS_VERSION}-rancheros
}

pvgrub_config()
{
    local grub_file=/mnt/new_img/boot/grub/menu.lst
cat > $grub_file<<EOF
default 0
timeout 0
#fallback 1

hiddenmenu

title RancherOS ${RANCHEROS_VERSION}-(current)
root (hd0)
kernel /boot/vmlinuz-${RANCHEROS_VERSION}-rancheros rancher.cloud_init.datasources=[ec2]
initrd /boot/initrd-${RANCHEROS_VERSION}-rancheros

EOF

if [ ! -z $ROLLBACK_VERSION ]; then
    sed -i 's/^#\(fallback\)/\1/' $grub_file
cat >> $grub_file<<EOF
title RancherOS ${ROLLBACK_VERSION}-(rollback)
root (hd0)
kernel /boot/vmlinuz-${ROLLBACK_VERSION}-rancheros rancher.cloud_init.datasources=[ec2]
initrd /boot/initrd-${ROLLBACK_VERSION}-rancheros
EOF
fi
}

format_and_mount()
{
    device_defined ${DEVICE}
    format_device
    mount_device
    trap "umount ${BASE_DIR}" EXIT
    create_boot_dirs
}

if [ -n ${ENV} ]; then
    case ${ENV} in
        "generic")
            format_and_mount
            install_grub
            grub2_config
            /scripts/seed-data $BASE_DIR $CLOUD_CONFIG
            ;;
        "amazon-ebs")
            format_and_mount
            pvgrub_config
            ;;
        "rancher-upgrade")
            mount_device 
            create_boot_dirs
            grub2_config
            pvgrub_config
            ;;
        *)
            echo "$ENV is not a valid environment" 1>&2
            exit 1
            ;;
    esac
fi

install_rancher
