#!/bin/bash

set -e
set -x

export DEVICE=${1}
export ENV=${2}
MOUNTS=""
BASE_DIR="/mnt/new_img"
VERSION=${RANCHEROS_VERSION}

if [[ -z $DEVICE ]]; then
    echo "Need to Pass a device name as arg1." 1>&2
    exit 1
fi

format_device()
{
    mkfs.ext4 -L RANCHER_STATE ${DEVICE}1
}

mount_device() 
{
    mkdir /mnt/new_img
    mount ${DEVICE}1 /mnt/new_img

    echo "/mnt/new_img"
}

create_boot_dirs()
{
    mkdir -p ${BASE_DIR}/boot/grub
}

install_grub() {
    grub-install --boot-directory=/mnt/new_img/boot ${DEVICE}
}

grub2_config(){
cat >${BASE_DIR}/boot/grub/grub.cfg <<EOF
set default="0"
set timeout="2"

menuentry "RancherOS" {
  set root=(hd0,1)
  linux /boot/vmlinuz-${RANCHEROS_VERSION}-rancheros
  initrd /boot/initrd-${RANCHEROS_VERSION}-rancheros
}
EOF
}

install_rancher()
{
    sudo cp /dist/initrd /mnt/new_img/boot/initrd-${RANCHEROS_VERSION}-rancheros
    sudo cp /dist/vmlinuz /mnt/new_img/boot/vmlinuz-${RANCHEROS_VERSION}-rancheros
}

pvgrub_config()
{
cat > /mnt/new_img/boot/grub/menu.lst <<EOF
default 0
timeout 0

hiddenmenu

title RancherOS ${RANCHEROS_VERSION}
root (hd0)
kernel /boot/vmlinuz-${RANCHEROS_VERSION}-rancheros rancher.cloud_init.datasources=[ec2]
initrd /boot/initrd-${RANCHEROS_VERSION}-rancheros

EOF
}

mount()
{
    export MOUNTS="$MOUNTS $(mount_device)"
    trap "umount ${MOUNTS}" EXIT
}

format_and_mount()
{
    format_device
    mount
    create_boot_dirs
}

if [ -n ${ENV} ]; then
    case ${ENV} in
        "virtualbox-iso")
            /scripts/set-disk-partions ${DEVICE}
            format_and_mount
            install_grub
            grub2_config
            /scripts/vagrant-seed-data /mnt/new_img
            ;;
        "amazon-ebs")
            format_and_mount
            pvgrub_config
            ;;
        "rancher-upgrade")
            mount 
            ;;
        *)
            echo "$ENV is not a valid environment" 1>&2
            exit 1
            ;;
    esac
fi

install_rancher
