#!/bin/bash

set -e -x

BASE_DIR=${1}
CLOUD_DATA=${2}

if [ -z $BASE_DIR ]; then
    echo "Need base directory to place files" 1>&2
    exit 1
fi

mkdir -p ${BASE_DIR}/lib/rancher/conf/cloud-config.d

cp ${CLOUD_DATA} ${BASE_DIR}/lib/rancher/conf/cloud-config.d/
